import Header from "@/components/Header"
import "./globals.css"
import { Inter } from "next/font/google"
import Footer from "@/components/Footer"
import ParticleBackground from "@/components/ParticlesBackground"
const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Khemraj Fekar",
  description: "Generated by Khemraj Fekar",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <ParticleBackground />
        <Footer />
      </body>
    </html>
  )
}
